# Where things are
sass:
  style: compact # possible values: nested expanded compact compressed
collections:
  posts:
    output: true
    permalink: /:collection/:name
  pages:
    output:    true
    permalink: /:path

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist

# Outputting
# permalink:        /:categories/:title
defaults:
  - scope:
      path:       ''
      type:       pages
    values:
      layout:     default

# jekyll-seo-tag
title:            Rime.co
tagline:          'Build Business with AI Powered Blog'
description:      'Introducing Arya, your personal blog manager.
  Business Focused - A weblog which connects your different content stream and bring (sync) all your posts in one place. Currently Rime support 11 services.
  Saves time - Our platform organizes your posts into collection and topics. Rime optimizes your weblog for search engines with updated standards. SEO includes meta tags, schema and AMP.
  Builds audience - Host the weblog on your custom domain which defines you completely. From top stories to latest posts, life events to places, everything in one place.'
baseurl:          /RhymeTek
# color:            DA2E75
twitter:
  username:       rimeofficial
  card:           summary
facebook:
  app_id:         510262139040639
  publisher:      297545803726080
  admins:         suvozit
logo:             /assets/images/logo-share.png
author:           Rhyme Tek.
image:
  twitter:        /assets/images/logo-share.png
  facebook:       /assets/images/logo-share.png
  height:         500
  width:          500
social:
  name: Rhyme Tek.
  links:
    - https://twitter.com/RhymeTek
    - https://www.facebook.com/RhymeTek
    - https://www.linkedin.com/in/RhymeTek
    - https://github.com/RhymeTek
    - https://keybase.io/RhymeTek
webmaster_verifications:
  google: KT5gs8h0wvaagLKAVWq8bbeNwnZZK1r1XQysX3xurLU
  bing: 1234
  alexa: 1234
  yandex: 1234
  baidu: 1234
lang: en_UK