# Environment Variables for application in development

FOO: BAR

oauth:
  be:
    id: DNN8X6LQIZRxBI1YDsZLAAkHQ1lcb4xt
    secret: 

  dp:
    id: jn044bxg0qxd43o
    secret: d42k59rvbk9f9ob

  fb:
    id: 846304802103036
    secret: 53dd173982249fe675b599582546d8c1

  fl:
    id: ddab09a3481d5d85ac333a2b70952229
    secret: aac84fbb58dee4f9

  fs:
    id: GI5UQ4ZFMND0OKUWSAN1TWM1GPLV335COYACKRD5U1DADOM1
    secret: EGIW14TUWBN155FYMRKFLRLHT25TKKMYYHKDC4NC2VD02VJH

  gh:
    id: 50d411f9334a42fcc751
    secret: dec2a9b279f983e71225a7e8f3e0e2fe7524b6a0

  go:
    id: 202356958127.apps.googleusercontecom
    secret: Dq49v-xnZOns_kLFO0scptN3
    yt_key: AI39si6OUedMCBFCvC83ceX1F0yhrLa22hz64M7foai77X_jhAytNIhvILXu9Op0k2FOLy4pYRbJZUh4OHyM2V8UJIIyYvA

  li:
    id: 81nybltzemk2v7
    secret: dGWuz6XsG0k6zpHy

  ig:
    id: f744926ac70948f8ac11b82255473b86
    secret: 527b35d693894efa90af5bf921874b5b

  ms:
    id: 0000000040103A2D
    secret: MjqqRifEPNjygdeW-HVDHUHVPZJMurhR

  tw:
    id: q9ssz77jlA23UMJucjhYtA
    secret: 3ipCvBYZL4ogaWPLdGSTdMwbeM3ONCFBWD6QcHeKo8Y

  tu:
    id: zJRgnOoaNeZKdb3yLD7WdeItjkEIf76bQeQNhODG9ZRipFyKsT
    secret: tmc9JPWLpL8ihSncdT53MvWindMw5ZThLJL8yD7vd6cvFPFvDS

  vi:
    id: 0b2700a2ea9c52ac1855db10194198a9a0fddbc9
    secret: 1c5754063aaf2f4ad91a9a646dd7f68496d4aece

api:
  bing: AnWLEJTvYM0b-v3uXLMD4VckmHWGnxj20lIOsT73gvR8akZhXibwFg-6kK4Ek
  ga: UA-41643154-1