- name: Username
  url: /settings # /username

- name: Account
  url: /settings/account

- name: Email
  url: /settings/email

- name: Notifications
  url: /settings/notifications

- name: Deactivite
  url: /settings/deactivate