- name: Avatar
  url: /settings/avatar

- name: Username
  url: /settings/username

- name: Account
  url: /settings/account

- name: Email
  url: /settings/email

- name: Notifications
  url: /settings/notifications

- name: Payment
  url: /settings/payment

- name: Deactivate
  url: /settings/deactivate

- name: Delete
  url: /settings/delete