- title: Username
  url: settings/username

- title: Account
  url: settings

- title: Email
  url: settings/email

- title: Notifications
  url: settings/notifications

- title: Deactivite
  url: settings/deactivate